//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Query.g by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace RSql4Net.Models.Queries {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="QueryParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public interface IQueryListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] QueryParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] QueryParser.SelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEval([NotNull] QueryParser.EvalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEval([NotNull] QueryParser.EvalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr([NotNull] QueryParser.OrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr([NotNull] QueryParser.OrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd([NotNull] QueryParser.AndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd([NotNull] QueryParser.AndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] QueryParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] QueryParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] QueryParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] QueryParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] QueryParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] QueryParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.comparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparator([NotNull] QueryParser.ComparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.comparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparator([NotNull] QueryParser.ComparatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.comp_fiql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_fiql([NotNull] QueryParser.Comp_fiqlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.comp_fiql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_fiql([NotNull] QueryParser.Comp_fiqlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.comp_alt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_alt([NotNull] QueryParser.Comp_altContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.comp_alt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_alt([NotNull] QueryParser.Comp_altContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReserved([NotNull] QueryParser.ReservedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReserved([NotNull] QueryParser.ReservedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.single_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_quote([NotNull] QueryParser.Single_quoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.single_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_quote([NotNull] QueryParser.Single_quoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.double_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble_quote([NotNull] QueryParser.Double_quoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.double_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble_quote([NotNull] QueryParser.Double_quoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] QueryParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] QueryParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] QueryParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] QueryParser.ValueContext context);
}
} // namespace RSql4Net.Models.Queries
