//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RSqlQuery.g by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace RSql4Net.Models.Queries {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RSqlQueryParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public interface IRSqlQueryVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelector([NotNull] RSqlQueryParser.SelectorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEval([NotNull] RSqlQueryParser.EvalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] RSqlQueryParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] RSqlQueryParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint([NotNull] RSqlQueryParser.ConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup([NotNull] RSqlQueryParser.GroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] RSqlQueryParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.comparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparator([NotNull] RSqlQueryParser.ComparatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.comp_fiql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp_fiql([NotNull] RSqlQueryParser.Comp_fiqlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.comp_alt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp_alt([NotNull] RSqlQueryParser.Comp_altContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReserved([NotNull] RSqlQueryParser.ReservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.single_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_quote([NotNull] RSqlQueryParser.Single_quoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.double_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble_quote([NotNull] RSqlQueryParser.Double_quoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] RSqlQueryParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RSqlQueryParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] RSqlQueryParser.ValueContext context);
}
} // namespace RSql4Net.Models.Queries
