//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RSqlQuery.g by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace RSql4Net.Models.Queries {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRSqlQueryListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public partial class RSqlQueryBaseListener : IRSqlQueryListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector([NotNull] RSqlQueryParser.SelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector([NotNull] RSqlQueryParser.SelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.eval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEval([NotNull] RSqlQueryParser.EvalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.eval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEval([NotNull] RSqlQueryParser.EvalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr([NotNull] RSqlQueryParser.OrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr([NotNull] RSqlQueryParser.OrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd([NotNull] RSqlQueryParser.AndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd([NotNull] RSqlQueryParser.AndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstraint([NotNull] RSqlQueryParser.ConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstraint([NotNull] RSqlQueryParser.ConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup([NotNull] RSqlQueryParser.GroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup([NotNull] RSqlQueryParser.GroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] RSqlQueryParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] RSqlQueryParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparator([NotNull] RSqlQueryParser.ComparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparator([NotNull] RSqlQueryParser.ComparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comp_fiql"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_fiql([NotNull] RSqlQueryParser.Comp_fiqlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comp_fiql"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_fiql([NotNull] RSqlQueryParser.Comp_fiqlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comp_alt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_alt([NotNull] RSqlQueryParser.Comp_altContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comp_alt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_alt([NotNull] RSqlQueryParser.Comp_altContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReserved([NotNull] RSqlQueryParser.ReservedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReserved([NotNull] RSqlQueryParser.ReservedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.single_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_quote([NotNull] RSqlQueryParser.Single_quoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.single_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_quote([NotNull] RSqlQueryParser.Single_quoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.double_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble_quote([NotNull] RSqlQueryParser.Double_quoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.double_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble_quote([NotNull] RSqlQueryParser.Double_quoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] RSqlQueryParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] RSqlQueryParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] RSqlQueryParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] RSqlQueryParser.ValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace RSql4Net.Models.Queries
