//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RSqlQuery.g by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace RSql4Net.Models.Queries {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RSqlQueryParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public interface IRSqlQueryListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelector([NotNull] RSqlQueryParser.SelectorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.selector"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelector([NotNull] RSqlQueryParser.SelectorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEval([NotNull] RSqlQueryParser.EvalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.eval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEval([NotNull] RSqlQueryParser.EvalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr([NotNull] RSqlQueryParser.OrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.or"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr([NotNull] RSqlQueryParser.OrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd([NotNull] RSqlQueryParser.AndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd([NotNull] RSqlQueryParser.AndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] RSqlQueryParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] RSqlQueryParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] RSqlQueryParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] RSqlQueryParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] RSqlQueryParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] RSqlQueryParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparator([NotNull] RSqlQueryParser.ComparatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comparator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparator([NotNull] RSqlQueryParser.ComparatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comp_fiql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_fiql([NotNull] RSqlQueryParser.Comp_fiqlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comp_fiql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_fiql([NotNull] RSqlQueryParser.Comp_fiqlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.comp_alt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_alt([NotNull] RSqlQueryParser.Comp_altContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.comp_alt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_alt([NotNull] RSqlQueryParser.Comp_altContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReserved([NotNull] RSqlQueryParser.ReservedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReserved([NotNull] RSqlQueryParser.ReservedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.single_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_quote([NotNull] RSqlQueryParser.Single_quoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.single_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_quote([NotNull] RSqlQueryParser.Single_quoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.double_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble_quote([NotNull] RSqlQueryParser.Double_quoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.double_quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble_quote([NotNull] RSqlQueryParser.Double_quoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] RSqlQueryParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] RSqlQueryParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSqlQueryParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] RSqlQueryParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSqlQueryParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] RSqlQueryParser.ValueContext context);
}
} // namespace RSql4Net.Models.Queries
